base_global_planner: "navfn/NavfnROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_trans: 0.5
  min_vel_trans: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false
  sim_time: 6.0 # Default 1.7, fails around 10.0
  sim_granularity: 0.25 # 0.025
  vx_samples: 10
  vy_samples: 10
  vtheta_samples: 20
  controller_frequency: 5.0 # Default 20.0
  path_distance_bias: 50.0 # Default 32.0
  goal_distance_bias: 30.0 # Default 24.0
  occdist_scale: 0.01
#  forward_point_distance: 0.325 # 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  oscillation_reset_dist: 0.05
  publish_cost_grid: true

global_costmap:
  global_frame: "odom"
  robot_base_frame: "base_link"
  update_frequency: 0.1 # Default 5.0
  publish_frequency: 0.1
  # Set the map area and adjust so it is centered around odom
  width: 10.0
  height: 10.0
  origin_x: -5.0
  origin_y: -5.0
#  static_map: true # Try later
  rolling_window: false # Try later
  plugins:
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
  observation_sources: scan
  scan: { sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true }
  footprint: [ [ -0.2, -0.2 ], [ -0.2, 0.2 ], [ 0.2, 0.2 ], [ 0.2, -0.2 ] ]
  footprint_padding: 0.05  # Optional padding around the footprint

local_costmap:
  global_frame: "odom" #
  robot_base_frame: "base_link"
  update_frequency: 2.0 # Default 5.0
  publish_frequency: 2.0
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  obstacle_layer:
    observation_sources: scan
    scan: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
    track_unknown_space: true
    obstacle_range: 5.0 # 2.5
    raytrace_range: 5.0 # 3.0
    clearing_threshold: 1.0  # Adjust to ensure obstacles are cleared quickly
    combination_method: 1
  inflation_layer:
    inflation_radius: 0.1  # Adjusts the gradient of the costmap
    cost_scaling_factor: 10.0
  footprint: [ [ -0.2, -0.2 ], [ -0.2, 0.2 ], [ 0.2, 0.2 ], [ 0.2, -0.2 ] ]
  footprint_padding: 0.05  # Optional padding around the footprint
