base_global_planner: "navfn/NavfnROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_trans: 0.5
  min_vel_trans: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false
  sim_time: 8.0 # Default 1.7, fails around 10.0
  sim_granularity: 0.025 # 0.025
  vx_samples: 10
  vy_samples: 10
  vtheta_samples: 20
  controller_frequency: 5.0 # Default 20.0
  path_distance_bias: 32.0 # Default 32.0
  goal_distance_bias: 24.0 # Default 24.0
  occdist_scale: 0.01
#  forward_point_distance: 0.325 # 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  oscillation_reset_dist: 0.05
  publish_cost_grid: true

global_costmap:
  global_frame: "world"
  robot_base_frame: "turtle2"
  update_frequency: 1.0 # Default 5.0
  publish_frequency: 1.0
  plugins:
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
  observation_sources: turtle2_scan
  turtle2_scan: { sensor_frame: turtle2, data_type: LaserScan, topic: /turtle2/scan, marking: true, clearing: true }


local_costmap:
  global_frame: "world" # Optionally change to odom later.
  robot_base_frame: "turtle2"
  update_frequency: 5.0 # Default 5.0
  publish_frequency: 5.0
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.05
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  obstacle_layer:
    observation_sources: turtle2_scan
    turtle2_scan: {sensor_frame: turtle2, data_type: LaserScan, topic: /turtle2/scan, marking: true, clearing: true}
    track_unknown_space: true
    obstacle_range: 3.0 # 2.5
    raytrace_range: 3.5 # 3.0
    clearing_threshold: 0.1  # Adjust to ensure obstacles are cleared quickly
    combination_method: 1
  inflation_layer:
    inflation_radius: 1.5  # Adjusts the gradient of the costmap
    cost_scaling_factor: 1.0

